name: "[DEV] Build and Publish iOS"
on: workflow_dispatch

jobs:
  # Build job
  build:
    runs-on: macos-latest
    steps:
      # Checks-out our repository under $GITHUB_WORKSPACE, so our job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install flutter
      - name: Flutter get
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.3"

      # Install your project's dependencies
      - run: flutter pub get

      - name: Install CocoaPods dependencies
        run: cd ios && pod install

      # Build and sign the ipa using a single flutter command
      - name: Building IPA
        run: flutter build ipa --release --no-codesign

      # Collect the file and upload as artifact
      - name: collect ipa artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-ipa
          # Path to the release files
          path: build/ios/ipa/*.ipa
